# A simple action usage
name: Build Kernel
on:
  workflow_dispatch:

jobs:
  Build-Kernel:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Build Kernel
        uses: wuwuming126/kernel_build_action@main
        with:
          kernel-url: https://github.com/oplus-giulia-dev/android_kernel_oneplus_sm8650         
          kernel-branch: lineage-23.0
          config: giulia_defconfig
          arch: arm64
          aosp-gcc: true
          aosp-clang: true
          ksu: true
          ksu-other:true
          ksu-url:https://github.com/KernelSU-Next/KernelSU-Next
          ksu-version: v1.1.1
          android-version: 16
          aosp-clang-version: r547379
          disable-lto: true
          anykernel3: true
